### ISSUE TITLE
`IllegalArgumentException` when calling `terminate` method on android

### ISSUE THREAD

**Issue by kduma** [TheeMachine/presentation-capacitor#7]
```
Serious error executing plugin
java.lang.IllegalArgumentException: Wrong number of arguments; expected 0, got 1
at java.lang.reflect.Method.invoke(Native Method)
at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)
at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by TheeMachine** [comment]
Merged your other commit and npm updated. version 0.1.5
